// https://png-pixel.com/
export const EmptyImages = {
  black:
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mMU/A8AAScBEsBwhbUAAAAASUVORK5CYII=",
  darker:
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mM0+Q8AAW0BNbM5dTkAAAAASUVORK5CYII=",
  dark:
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mN0+Q8AAY0BRWNDFkgAAAAASUVORK5CYII=",
  medium:
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mMM+A8AAaUBUZYFVPwAAAAASUVORK5CYII=",
  light:
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNM+A8AAcUBYdGWbZ0AAAAASUVORK5CYII=",
  lighter:
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mMs/Q8AAe8BduVMpHAAAAAASUVORK5CYII=",
  white:
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mO8ceXKfwAIjQOBak1kGwAAAABJRU5ErkJggg==",
};
